### ISSUE TITLE
[Refactoring] Refactor to work with kaskadi-stock-update-lambda

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/kaskadi-stock-report-lambda#2]
Refactoring on going.

Extracting the stock update as a standalone lambda that can be called by authenticated API requests and is also ran once a week (Mondays at 7AM).

This stock update lambda is then posting to an SNS topic (if it has been triggered by the scheduled event!) to which our current reporter should attach itself.

This allows decoupling of logic between stock update and stock reporting.

It also simplifies the code as stock updating would pull data from service providers to update our DB. The reporting lambda then only needs to read from our DB to have all information (instead of processing data like now).

**Comment by alexlemaire** [comment]
`kaskadi-stock-update-lambda` is in place and working. Can be called via HTTP (pass array of warehouses to update in `body` or pass `['*']` to update all warehouses from the DB) **and** is running every week on Monday at 7AM.

Will refactor `kaskadi-stock-report-lambda` to be triggered via the topic where `kaskadi-stock-update-lambda` publishes once a week so that it pulls from the DB the latest stocks and report it to all subscribers of its topic

**Comment by Holger-Will** [comment]
wait, before you make architectural changes like this, please talk to me first. 
For this special case, you are completely right, factoring out common code is a good idea.
But please come up with at least three ways to do this (andd tell me) so we can decide what the best approach is.

- i don't like the idea of having a monolithic updater where all API handler for different APIs (AMZ, YSWS, etc) live...
- I'm not sure we really need Pub/Sub here...
- The call to the Wemalo API is overcomplicating things as far as i can tell... but before do concrete code review let's first get the approach right...

as i have a meeting at 12:00, so let's have a slack meeting as early as possible. maybe at 9:00, let me know when you are available.

**Comment by alexlemaire** [comment]
**Update post Slack meeting**:

- implemented one lambda (`kaskadi-get-ysws-stocks-lambda`) that:
  - reads from ES the last time we updated the stocks for YSWS (I stored the info in the `warehouses` index in the field `stocks_last_updated`)
  - calls Wemalo API `availableStocks()` endpoint to get the stocks changes since last update
  - **If** there are any changes in stocks since last update then we invoke `kaskadi-update-stocks-lambda` to update stocks in DB

This lambda runs on demand via the endpoint `https://api.klimapartner.net/stocks/update/ysws` and also every Monday at 6:55AM (so stocks should be up to date for the reporting at 7AM)

- implemented one lambda (`kaskadi-update-stocks-lambda`) that:
  - reads its payload + do a `bulk` update of our DB with the info from `stockData` for the given `warehouse`
  - updates `stocks_last_updated` field from the given `warehouse` in the `warehouses` index

The input is as following:
```
{
  stockData: [
    {
      id: bla,
      quantity: 100
    },
    {
      id: hey,
      quantity: 200
    }
  ],
  warehouse: 'warehouse_name'
}
```
- updated the original `kaskadi-stock-report-lambda` to simply read stock info from our DB

Leaving this open for further discussion, will close the issues on the other repo.

**Comment by alexlemaire** [comment]
Closing this now, feedback given [here](https://github.com/kaskadi/kaskadi-update-stocks-lambda/issues/1) and [there](https://github.com/kaskadi/kaskadi-get-ysws-stocks-lambda/issues/12).

Will do PRs for future updates to centralized discussion
