### ISSUE TITLE
usecases

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-stock-report-lambda#3]
still not sure we need pub/sub here... what are the usecases?

for now this is used to send emails, right? as long as there is no other usecase, we can send emails here directly...

**Comment by alexlemaire** [comment]
Yep I'm just using it to send email notifications. The only advantage for me was that with 1 publish it would send to all subscribers so it's a bit easier to manage in case we have multiple people that needs this kind of information (for now it's only me for testing and Juliane that are subscribed)

**Comment by Holger-Will** [comment]
yeah, in the end this should be a setting in our user table, so you would just get all user with a specific key set from ES and send the email to them...

**Comment by alexlemaire** [comment]
Should I updated this to work with [sendemail](https://www.npmjs.com/package/sendmail) and start building a user table that we can then also use for our passwordless authentication via email?

I can also implement the passwordless flow if you're decided to go for this

**Comment by Holger-Will** [comment]
> Should I update this to work with sendemail then and start building a user table that we can use for our passwordless authentication via email?

yes

> I can also implement the passwordless flow if you're decided to go for this

not yet

**Comment by alexlemaire** [comment]
Alright I made the switch to use `sendmail` instead.

You can see the PR [here](https://github.com/kaskadi/kaskadi-stock-report-lambda/pull/4)

**Comment by alexlemaire** [comment]
Closing this now, PR has been approved and merged a while ago, just forgot to close the issue.
